# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c678122b33a833d0d5f23b93666d50d3f4f3753d85cbd0deff9af3cef35bfa370845cdeff514e7bc9c0053ea0f03c50334bc988a911ad78419c28f032d9c15

test:
  secret_key_base: 47563031eed6094474ad6a7471060f238dadf90a9b798d87f63256c8ab17b59db246481e1afbd58826879f8959f68dd830237fad27bfdfd5f61aa33a62d98774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
